### ISSUE TITLE
Fetch Crashes with CL limits (*-95001) or(94888-95000) and similar

### ISSUE THREAD

**Issue by GafgarD** [daGnutt/satisfactory-crashhandler#5]
:D would be nice

**Comment by daGnutt** [comment]
One of the biggest problems (is my problem for choosing a poor datastore to begin with) is that FireStore does not have support for "OR" in their query language. For ORing queries, you should currently do both queries and combine them yourself.

Also you cannot query without setting an index per query. Considering moving storage to Cloud SQL. The requirements of the database are moving more and more into a relational system.

**Comment by GafgarD** [comment]
I didn't mean or like in the query :) just wrote two examples of like how to define a range. One with an undefined min CL, and one with a fixed range. But we don't need to be able to use "or" as a command imo

**Comment by daGnutt** [comment]
With current datastructure it is not possible to serverside filter on the CL's.
That filtering must be done after data has been fetched. It will not be included in the tool for backend working, filtering should instead be done locally by the client viewing.
